### ISSUE TITLE
[NEED ASSIST] 

### ISSUE THREAD

**Issue by mkcpb** [Adyen/adyen-networking-ios#25]
**Describe the challenge**
When I updated Adyen SDK pod to 5.0.0 and installed AdyenNetworking to 1.0.0 I'm got an error which can be seen on screenshoot. In near future we will need to replace the classic Checkout SDK with Drop-In or Component so it requires the Adyen iOS client-side library version to be at least 5.0.0. What can be the problem?

**Screenshots**
<img width="1103" alt="Screenshot 2023-03-15 at 15 27 02" src="https://user-images.githubusercontent.com/92429728/225341161-e27caa2d-30e2-49fa-80b5-b7713b60636d.png">

**Comment by descorp** [comment]
Hey @mkcpb 

Thank you for your feedback!

> What can be the problem?

We have not tested our SDK as part of the iOS application extension, hence did not expect that `UIApplication.shared` would cause any trouble 😅

The good news is - this code was removed from [v2.0.0](https://github.com/Adyen/adyen-networking-ios/commit/121791ac1563670c944c2d31155ee79a9ad89c5a#diff-9172a322e1e35ee5efc77cf892121f0964e8e55ee6fb58d5959d5705cba3fd97L150-L154).
We only need to update [Adyen iOS Drop-in and Components](https://github.com/Adyen/adyen-ios) to AdyenNetworking 2.0.0. 
Keep an eye on version 5.2.0.

---

I am going to close this ticket, since it is not in a scope of `AdyenNetworking` repo.
If you want, feel free to create a new issue for the "Drop-in and Components" repo so we can ping you ASA new version is released.
